# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run build
  displayName: 'npm install and build'

- task: test@0
  inputs:
    versionSpec: '10.x'
  - script: |
    npm install
    npm run test:all
  displayName: 'test ant-design-pro'